# Generated by Django 4.2.3 on 2023-08-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='', max_length=2000)),
            ],
            options={
                'db_table': 'myblog_contact',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=45, unique=True)),
                ('email', models.EmailField(default='', max_length=45)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=45)),
            ],
            options={
                'db_table': 'myblog_user',
            },
        ),
        migrations.AddConstraint(
            model_name='userdata',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
