# Generated by Django 4.2.3 on 2023-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
    ]
