# Generated by Django 4.2.3 on 2023-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_signup_unique_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
