# Generated by Django 4.2.3 on 2023-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_alter_userdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='', max_length=45, primary_key=True, serialize=False),
        ),
    ]
