# Generated by Django 4.2.3 on 2023-07-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_user_unique_user_alter_user_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
