# Generated by Django 4.2.3 on 2023-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_user_password_alter_user_age_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
