# Generated by Django 4.2.3 on 2023-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_user_id_alter_user_age_alter_user_email_and_more'),
    ]

    operations = [
        
        migrations.AlterModelTable(
            name='user',
            table='myblog_user',
        ),
    ]
