# Generated by Django 4.2.3 on 2023-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_user_id_alter_user_table'),
    ]

    operations = [
        
    ]
