# Generated by Django 4.2.3 on 2023-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_user_id'),
    ]

    operations = [
   
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
    ]
