# Generated by Django 4.2.3 on 2023-07-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_user_id_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
    ]
