# Generated by Django 4.2.3 on 2023-08-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='myblog_contact',
        ),
    ]
