# Generated by Django 4.2.3 on 2023-08-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
