# Generated by Django 4.2.3 on 2023-08-02 09:40

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_delete_userdata_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=30, verbose_name=django.contrib.auth.models.User)),
                ('email', models.EmailField(default='', max_length=50)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'myblog_user',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddConstraint(
            model_name='userdata',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
