# Generated by Django 4.2.3 on 2023-08-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0023_userdata_delete_user_userdata_unique_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='last_login',
        ),
    ]
